Switch to hardhat-deploy
yieldgate/yieldgate pull request #49
Opened 2022-08-15 13:28 UTC by wottpal

Resolves #37 

No review is needed yet. I track progress in #37.

2022-08-17 15:06 UTC, sebastianst requested changes
Looks great! Only some minor improvement proposals.

2022-08-17 16:33 UTC, wottpal commented on packages/contracts/deploy/001_deploy_yieldgate.ts
> +  await deploy('YieldGate', {
Typescript doesn't allow me to do so. The `DeployFunction` has the following return type: `Promise<void | boolean>`. Just FYI by returning nothing in an async function right now it's implicitly `Promise<void>` at the moment.

[I found this example](https://github.com/wighawag/template-ethereum-contracts/blob/96e7e12528dfeefd167cdf78fd0700286b068ccd/deploy/002_deploy_greetings_registry.ts#L19) out there, but I'm not sure what they are achieving by this (but also didn't spend too much time studying the docs).

2022-08-17 16:37 UTC, sebastianst commented on packages/contracts/deploy/001_deploy_yieldgate.ts
> +  await deploy('YieldGate', {
ok thanks, was just curious.

2022-08-17 16:38 UTC, wottpal commented on packages/contracts/.gitignore
> +coverage.json
See https://github.com/yieldgate/yieldgate/pull/49/commits/01e90d50c51e05a1c464525a1311eb5077727a45 where I'm improving all the ignore files you are mentioning. But please, let us only leave the `.env` in the hardhat `.gitignore`. Long story, but I already lost some money by leaking a private key... 🙈

If you are d'accord please also resolve the other comments.

2022-08-17 18:24 UTC, sebastianst commented on packages/contracts/.gitignore
> +coverage.json
haha sure thing 💸

2022-08-17 18:56 UTC, wottpal commented on packages/frontend/src/components/creator/CreatorCardActions.tsx
> +    if (!poolAddress || BigNumber.from(poolAddress).eq(0)) {
Awesome, thank you! Actually, I even googled for something like this during implementation but couldn't find something. Updated in https://github.com/yieldgate/yieldgate/pull/49/commits/31dc08c64b13434447915d69911482512f5271cd

2022-08-18 05:49 UTC, wottpal commented on packages/frontend/src/components/creator/CreatorCardActions.tsx
> +      ) as BeneficiaryPool
Thanks for bringing this up. I updated the syntax everywhere in https://github.com/yieldgate/yieldgate/pull/49/commits/9fdd4281286e03c189fc4ba4a3570055a813af95

2022-08-20 14:14 UTC, sebastianst approved these changes

2022-08-20 14:15 UTC, merged